### ISSUE TITLE
Crash when there is only 2 powers in the Kanai Cube

### ISSUE THREAD

**Issue by Finrod927** [zetoken/D3-Android-by-ZTn#10]
I currently have only 2 items in the Kanai Cube (weapon and armor, no jewel).
When I go to the skills tab, and scroll to the bottom to my empty third slot of the cube, it just crashes.

LG G2 (French), Android 4.4.2
D3 Calculator 1.4.0

**Comment by zetoken** [comment]
Sorry for the delay, the fix is set for the next apk update (soon).
